# Make fot libtest
lib.name = sigtoint

# Source file
class.sources = sigtoint.c

# Inculding other files
datafiles = sigtoint-help.pd

include ../../Downloads/pd-lib-builder-master/Makefile.pdlibbuilder
